### ISSUE TITLE
Images missing max-width property

### ISSUE THREAD

**Issue by paskal** [kritoke/darksimplicity#3]
Hello!

I've stumbled upon the very same issue as the https://github.com/dim0627/hugo_theme_beg/issues/19:
![image](https://user-images.githubusercontent.com/712534/37658110-d7502c1a-2c5d-11e8-98d5-8b3bb46f3aa2.png)
The text won't wrap as well.
Also code example is not scrollable by itself but makes whole page scrollable:
![image](https://user-images.githubusercontent.com/712534/37658185-0203be0e-2c5e-11e8-8860-498abfb5110d.png)
Code of this example:

    ``` json
    {
        "shell":true,
        "cmd": ["rsync -az '$file' server.example.org:~ && ssh server.example.org 'chmod +x ./$file_name; ./$file_name'"],
    }
    ```

Here is my blog [source](https://github.com/paskal/terrty/tree/master/blog)  to replicate problems.

**Comment by kritoke** [comment]
Issue should be fixed with latest release.
