### ISSUE TITLE
Posts don't render if added as "posts" instead of "post"

### ISSUE THREAD

**Issue by DestyNova** [kritoke/darksimplicity#5]
I followed the hugo quickstart and added darksimplicity as the site theme, but found that none of my posts showed up.

It seems to be due to the following instruction in the quickstart:

```
hugo new posts/my-first-post.md
```

This creates a file in the `content/posts/`directory. However I can see on the example theme site that posts are in the `content/post/` directory. If I rename the directory then my posts appear. I tried another theme and it seems to work with both directory names.

I'm not sure what the real difference between "posts" and "post" is, but perhaps a note in the documentation would clarify for newcomers like myself?

**Comment by kritoke** [comment]
I reworked some of the files to allow either post or posts as content type.  Should be fixed now in the latest release.
